--AUTOMATICALLY GENERATED INSERTS USING USR_SY_GENERATE_DATA_INSERT_STMTS
--INSERT INTO TABLE: USR_CPHIVE_SUBSCRIPTION
--WITH FILTER: NONE
--PK FORMULA: SCOPE
--PK FORMULA_NEW: REPLACE('SCOPE = ''<SCOPE>''', '<SCOPE>', SCOPE)
--PRINTED ON: Aug 29 2019  9:32AM


--STEP 1 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'customer/category/created'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'customer/category/created' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 2 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'customer/category/deleted'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'customer/category/deleted' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 3 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'customer/category/updated'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'customer/category/updated' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 4 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'customer/created'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'customer/created' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		'AR_CUST.IS_ECOMM_CUST = ''Y'' AND EMAIL_ADRS_1 IS NOT NULL' AS FILTER


--STEP 5 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'customer/deleted'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'customer/deleted' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 6 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'customer/updated'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'customer/updated' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		'AR_CUST.IS_ECOMM_CUST = ''Y'' AND EMAIL_ADRS_1 IS NOT NULL' AS FILTER


--STEP 7 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'giftcard/created'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'giftcard/created' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 8 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'giftcard/deleted'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'giftcard/deleted' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 9 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'giftcard/updated'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'giftcard/updated' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 10 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'location/created'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'location/created' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 11 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'location/deleted'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'location/deleted' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 12 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'location/updated'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'location/updated' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 13 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'payment/method/created'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'payment/method/created' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 14 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'payment/method/deleted'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'payment/method/deleted' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 15 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'payment/method/updated'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'payment/method/updated' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 16 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'product/created'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'product/created' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		'IM_ITEM.IS_ECOMM_ITEM = ''Y''' AS FILTER


--STEP 17 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'product/deleted'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'product/deleted' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 18 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'product/ecommcategory/created'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'product/ecommcategory/created' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 19 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'product/ecommcategory/deleted'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'product/ecommcategory/deleted' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 20 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'product/ecommcategory/updated'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'product/ecommcategory/updated' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 21 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'product/inventory/created'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'product/inventory/created' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		'EXISTS (SELECT TOP 1 1 FROM IM_ITEM WHERE IM_ITEM.ITEM_NO = IM_INV.ITEM_NO AND IM_ITEM.IS_ECOMM_ITEM = ''Y'')' AS FILTER


--STEP 22 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'product/inventory/deleted'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'product/inventory/deleted' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 23 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'product/inventory/updated'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'product/inventory/updated' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		'EXISTS (SELECT TOP 1 1 FROM IM_ITEM WHERE IM_ITEM.ITEM_NO = IM_INV.ITEM_NO AND IM_ITEM.IS_ECOMM_ITEM = ''Y'')' AS FILTER


--STEP 24 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'product/updated'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'product/updated' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		'IM_ITEM.IS_ECOMM_ITEM = ''Y''' AS FILTER


--STEP 25 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'product/variant/inventory/created'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'product/variant/inventory/created' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		'EXISTS (SELECT TOP 1 1 FROM IM_ITEM WHERE IM_ITEM.ITEM_NO = IM_INV_CELL.ITEM_NO AND IM_ITEM.IS_ECOMM_ITEM = ''Y'')' AS FILTER


--STEP 26 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'product/variant/inventory/deleted'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'product/variant/inventory/deleted' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 27 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'product/variant/inventory/updated'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'product/variant/inventory/updated' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		'EXISTS (SELECT TOP 1 1 FROM IM_ITEM WHERE IM_ITEM.ITEM_NO = IM_INV_CELL.ITEM_NO AND IM_ITEM.IS_ECOMM_ITEM = ''Y'')' AS FILTER


--STEP 28 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'release/ticket/created'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'release/ticket/created' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 29 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'release/ticket/deleted'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'release/ticket/deleted' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 30 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'release/ticket/updated'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'release/ticket/updated' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 31 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'shipping/method/created'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'shipping/method/created' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 32 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'shipping/method/deleted'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'shipping/method/deleted' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 33 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'shipping/method/updated'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'shipping/method/updated' AS SCOPE,
		'Y' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER

--STEP 31 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'ecommcategory/assignment/created'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'ecommcategory/assignment/created' AS SCOPE,
		'N' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 32 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'ecommcategory/assignment/deleted'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'ecommcategory/assignment/deleted' AS SCOPE,
		'N' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER

--STEP 31 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'locationgroup/created'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'locationgroup/created' AS SCOPE,
		'N' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 32 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'locationgroup/deleted'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'locationgroup/deleted' AS SCOPE,
		'N' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 33 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'locationgroup/updated'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'locationgroup/updated' AS SCOPE,
		'N' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER

--STEP 31 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'product/kit/created'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'product/kit/created' AS SCOPE,
		'N' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 32 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'product/kit/deleted'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'product/kit/deleted' AS SCOPE,
		'N' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER


--STEP 33 OF 33
IF(NOT EXISTS (SELECT TOP 1 1 FROM dbo.USR_CPHIVE_SUBSCRIPTION WHERE 1=1 AND SCOPE = 'product/kit/updated'))
    INSERT INTO dbo.USR_CPHIVE_SUBSCRIPTION (
		SCOPE, 
		SUBSCRIBED, 
		LST_MAINT_DT, 
		FILTER)
    SELECT 
		'product/kit/updated' AS SCOPE,
		'N' AS SUBSCRIBED,
		NULL AS LST_MAINT_DT,
		NULL AS FILTER



