--Created Via Ezno package. Package created on 7/31/2019. Trigger was last modified on: 7/30/2019 5:15:05 PM
IF EXISTS (SELECT name FROM sysobjects WHERE name = N'USR_PS_DOC_PKG_TRK_NO_CPHIVE_INS')
DROP TRIGGER [dbo].[USR_PS_DOC_PKG_TRK_NO_CPHIVE_INS]
GO
-- =============================================
-- Author:		Vance Berisford
-- Create date: 6/20/2019
-- Description:	
-- =============================================
CREATE TRIGGER [dbo].[USR_PS_DOC_PKG_TRK_NO_CPHIVE_INS] 
   ON  [dbo].[PS_DOC_PKG_TRK_NO] 
   AFTER INSERT
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    --We only support singleton inserts. Mass inserts will need to be broken up.
	IF((SELECT COUNT(*) FROM INSERTED) <> 1)
		RETURN

	DECLARE @DOC_ID T_DOC_ID, @PKG_TRK_SEQ_NO T_SEQ_NO
	SELECT TOP 1 @DOC_ID = DOC_ID, @PKG_TRK_SEQ_NO = PKG_TRK_SEQ_NO
	FROM INSERTED

	--If this is not a release ticket, there is nothing to create.
	IF(NOT EXISTS (SELECT TOP 1 1 FROM VI_PS_DOC_HDR WHERE DOC_ID = @DOC_ID AND DOC_TYP = 'T' AND ORIG_ORD_DOC_ID IS NOT NULL AND IS_REL_TKT = 'Y'))
		RETURN

	DECLARE @UPD_TYP T_FLG, @UPD_TABLE T_DESCR
	SET @UPD_TABLE = 'release/ticket'

	SET @UPD_TYP = 'I'
	--IF(@DocAction = 'N')
	--	BEGIN
	--	SET @UPD_TYP = 'I'
	--	END
	--ELSE
	--	BEGIN
	--	SET @UPD_TYP = 'U'
	--	END

	DECLARE @SCOPE VARCHAR(1000)
	SET @SCOPE = @UPD_TABLE + '/' + CASE WHEN @UPD_TYP = 'I' THEN 'created' WHEN @UPD_TYP = 'U' THEN 'updated' ELSE 'deleted' END

	DECLARE @SUBSCRIBED T_BOOL, @FILTER T_SQL_FILTER
	SELECT @SUBSCRIBED = SUBSCRIBED, @FILTER = [FILTER] FROM USR_CPHIVE_SUBSCRIPTION WHERE SCOPE = @SCOPE

	IF(COALESCE(@SUBSCRIBED, 'N') = 'N')
		RETURN
	IF EXISTS(SELECT name FROM tempdb..sysobjects WHERE name = '##TMP_UPDATED_REL_TKT')
	  DROP TABLE [##TMP_UPDATED_REL_TKT]
	CREATE TABLE [##TMP_UPDATED_REL_TKT] (
		[UPD_PK] [varchar] (800) NULL
	)

	IF(@FILTER IS NULL)
		BEGIN
		INSERT INTO [##TMP_UPDATED_REL_TKT]
		SELECT DISTINCT '{"DOC_ID":"' + CAST(@DOC_ID AS VARCHAR(20)) + '"}' AS UPD_PK
		END
	ELSE
		BEGIN
		DECLARE @SQL VARCHAR(MAX)
		SET @SQL = 'INSERT INTO [#TMP_UPDATED_SY_GFC]
		SELECT DISTINCT ''{"DOC_ID":"' + CAST(@DOC_ID AS VARCHAR(20)) + '"}'' AS UPD_PK
		FROM PS_DOC_HDR WHERE PS_DOC_HDR = ' + CAST(@DOC_ID AS VARCHAR(20)) + ' AND ' + @FILTER
		EXEC(@SQL)
		END

	UPDATE USR_CPHIVE_QUEUE
	SET UPD_DT = GETDATE(),
		UPD_TYP = @UPD_TYP,
		ATTEMPTS = 0,
		RETRY_DT = NULL
	FROM [##TMP_UPDATED_REL_TKT] UPDATED
	WHERE USR_CPHIVE_QUEUE.UPD_TABLE = @UPD_TABLE
		AND UPDATED.UPD_PK = USR_CPHIVE_QUEUE.UPD_PK

    INSERT INTO USR_CPHIVE_QUEUE (UPD_TABLE, UPD_PK, UPD_DT, UPD_TYP)
	SELECT @UPD_TABLE, UPD_PK, GETDATE(), @UPD_TYP
	FROM [##TMP_UPDATED_REL_TKT] UPDATED
	WHERE NOT EXISTS (SELECT TOP 1 1 FROM USR_CPHIVE_QUEUE 
		WHERE USR_CPHIVE_QUEUE.UPD_TABLE = @UPD_TABLE 
			AND UPDATED.UPD_PK = USR_CPHIVE_QUEUE.UPD_PK)
END
