--Created Via Ezno package. Package created on 7/31/2019.
/*
 * Creating table USR_CPHIVE_SUBSCRIPTION
 *
 */
IF(NOT EXISTS(SELECT TOP 1 1 FROM Information_Schema.Tables WHERE TABLE_NAME = 'USR_CPHIVE_SUBSCRIPTION')) 
    BEGIN
    CREATE TABLE [dbo].[USR_CPHIVE_SUBSCRIPTION](
        [SCOPE] varchar(255) NOT NULL,
    CONSTRAINT [PK_USR_CPHIVE_SUBSCRIPTION] PRIMARY KEY CLUSTERED 
    (
        [SCOPE] ASC
    )
    ) ON [PRIMARY]
    END
GO


IF(NOT EXISTS(SELECT TOP 1 1 FROM Information_schema.Columns C WHERE C.TABLE_NAME = 'USR_CPHIVE_SUBSCRIPTION' AND C.COLUMN_NAME = 'SUBSCRIBED')) 
    BEGIN
    ALTER TABLE [dbo].[USR_CPHIVE_SUBSCRIPTION] ADD [SUBSCRIBED] T_BOOL NULL
    END
GO


IF(NOT EXISTS(SELECT TOP 1 1 FROM Information_schema.Columns C WHERE C.TABLE_NAME = 'USR_CPHIVE_SUBSCRIPTION' AND C.COLUMN_NAME = 'LST_MAINT_DT')) 
    BEGIN
    ALTER TABLE [dbo].[USR_CPHIVE_SUBSCRIPTION] ADD [LST_MAINT_DT] T_DT NULL
    END
GO


IF(NOT EXISTS(SELECT TOP 1 1 FROM Information_schema.Columns C WHERE C.TABLE_NAME = 'USR_CPHIVE_SUBSCRIPTION' AND C.COLUMN_NAME = 'FILTER')) 
    BEGIN
    ALTER TABLE [dbo].[USR_CPHIVE_SUBSCRIPTION] ADD [FILTER] T_SQL_FILTER NULL
    END
GO