--Created Via Ezno package. Package created on 7/31/2019.
/*
 * Creating table USR_CPHIVE_QUEUE
 *
 */
IF(NOT EXISTS(SELECT TOP 1 1 FROM Information_Schema.Tables WHERE TABLE_NAME = 'USR_CPHIVE_QUEUE')) 
    BEGIN
    CREATE TABLE [dbo].[USR_CPHIVE_QUEUE](
        [UPD_TABLE] T_DESCR NOT NULL,
        [UPD_PK] varchar(800) NOT NULL,
    CONSTRAINT [PK_USR_CPHIVE_QUEUE] PRIMARY KEY CLUSTERED 
    (
        [UPD_TABLE] ASC,
        [UPD_PK] ASC
    )
    ) ON [PRIMARY]
    END
GO


IF(NOT EXISTS(SELECT TOP 1 1 FROM Information_schema.Columns C WHERE C.TABLE_NAME = 'USR_CPHIVE_QUEUE' AND C.COLUMN_NAME = 'UPD_DT')) 
    BEGIN
    ALTER TABLE [dbo].[USR_CPHIVE_QUEUE] ADD [UPD_DT] T_DT NULL
    END
GO


IF(NOT EXISTS(SELECT TOP 1 1 FROM Information_schema.Columns C WHERE C.TABLE_NAME = 'USR_CPHIVE_QUEUE' AND C.COLUMN_NAME = 'UPD_TYP')) 
    BEGIN
    ALTER TABLE [dbo].[USR_CPHIVE_QUEUE] ADD [UPD_TYP] T_FLG NULL
    END
GO


IF(NOT EXISTS(SELECT TOP 1 1 FROM Information_schema.Columns C WHERE C.TABLE_NAME = 'USR_CPHIVE_QUEUE' AND C.COLUMN_NAME = 'ATTEMPTS')) 
    BEGIN
    ALTER TABLE [dbo].[USR_CPHIVE_QUEUE] ADD [ATTEMPTS] T_INT NULL
    END
GO


IF(NOT EXISTS(SELECT TOP 1 1 FROM Information_schema.Columns C WHERE C.TABLE_NAME = 'USR_CPHIVE_QUEUE' AND C.COLUMN_NAME = 'RETRY_DT')) 
    BEGIN
    ALTER TABLE [dbo].[USR_CPHIVE_QUEUE] ADD [RETRY_DT] T_DT NULL
    END
GO


IF(NOT EXISTS(SELECT TOP 1 1 FROM Information_schema.Columns C WHERE C.TABLE_NAME = 'USR_CPHIVE_QUEUE' AND C.COLUMN_NAME = 'IS_PROCESSING')) 
    BEGIN
    ALTER TABLE [dbo].[USR_CPHIVE_QUEUE] ADD [IS_PROCESSING] T_BOOL NULL
    END
GO


IF(NOT EXISTS (SELECT TOP 1 1 FROM sysobjects WHERE xtype = 'D' AND name = 'DF_USR_CPHIVE_QUEUE_IS_PROCESSING'))
		BEGIN
		ALTER TABLE [dbo].[USR_CPHIVE_QUEUE] ADD  CONSTRAINT [DF_USR_CPHIVE_QUEUE_IS_PROCESSING]  DEFAULT ('N') FOR [IS_PROCESSING]
		UPDATE [dbo].[USR_CPHIVE_QUEUE] SET [IS_PROCESSING] = ('N') WHERE [IS_PROCESSING] IS NULL
		END