--Previous versions of CPHive had different names for some of these objects. We want to drop them, and in the case of USR_C5_SUBSCRIPTION, convert the existing data

--DROP OLD TRIGGERS IF THEY EXIST
IF EXISTS (SELECT name FROM sysobjects WHERE name = N'USR_SY_STC_C5_QUEUE')
	DROP TRIGGER [dbo].[USR_SY_STC_C5_QUEUE]
IF EXISTS (SELECT name FROM sysobjects WHERE name = N'USR_SY_SHIP_VIA_COD_C5_QUEUE')
	DROP TRIGGER [dbo].[USR_SY_SHIP_VIA_COD_C5_QUEUE]
IF EXISTS (SELECT name FROM sysobjects WHERE name = N'USR_SY_PAY_COD_C5_QUEUE')
	DROP TRIGGER [dbo].[USR_SY_PAY_COD_C5_QUEUE]
IF EXISTS (SELECT name FROM sysobjects WHERE name = N'USR_SY_GFC_C5_QUEUE')
	DROP TRIGGER [dbo].[USR_SY_GFC_C5_QUEUE]
IF EXISTS (SELECT name FROM sysobjects WHERE name = N'USR_IM_SKU_TR_C5_QUEUE')
	DROP TRIGGER [dbo].[USR_IM_SKU_TR_C5_QUEUE]
IF EXISTS (SELECT name FROM sysobjects WHERE name = N'USR_IM_LOC_C5_QUEUE')
	DROP TRIGGER [dbo].[USR_IM_LOC_C5_QUEUE]
IF EXISTS (SELECT name FROM sysobjects WHERE name = N'USR_IM_ITEM_COD_C5_QUEUE')
	DROP TRIGGER [dbo].[USR_IM_ITEM_COD_C5_QUEUE]
IF EXISTS (SELECT name FROM sysobjects WHERE name = N'USR_IM_INV_CELL_COD_C5_QUEUE')
	DROP TRIGGER [dbo].[USR_IM_INV_CELL_COD_C5_QUEUE]
IF EXISTS (SELECT name FROM sysobjects WHERE name = N'USR_IM_INV_COD_C5_QUEUE')
	DROP TRIGGER [dbo].[USR_IM_INV_COD_C5_QUEUE]
IF EXISTS (SELECT name FROM sysobjects WHERE name = N'USR_EC_CATEG_C5_QUEUE')
	DROP TRIGGER [dbo].[USR_EC_CATEG_C5_QUEUE]
IF EXISTS (SELECT name FROM sysobjects WHERE name = N'USR_AR_CUST_C5_QUEUE')
	DROP TRIGGER [dbo].[USR_AR_CUST_C5_QUEUE]
IF EXISTS (SELECT name FROM sysobjects WHERE name = N'USR_AR_CATEG_COD_C5_QUEUE')
	DROP TRIGGER [dbo].[USR_AR_CATEG_COD_C5_QUEUE]

--If the old subscriptiont table exists, copy the values from it.
IF(EXISTS(SELECT TOP 1 1 FROM Information_Schema.Tables WHERE TABLE_NAME = 'USR_C5_SUBSCRIPTION')) 
	BEGIN

	IF(EXISTS(SELECT TOP 1 1 FROM Information_Schema.COLUMNS WHERE TABLE_NAME = 'USR_C5_SUBSCRIPTION' and COLUMN_NAME = 'FILTER')) 
		BEGIN
		DECLARE @SQL VARCHAR(2000)
		SELECT @SQL  = 'INSERT INTO [dbo].[USR_CPHIVE_SUBSCRIPTION]
			   ([SCOPE]
			   ,[SUBSCRIBED]
			   ,[LST_MAINT_DT]
			   ,[FILTER])
		SELECT	[SCOPE]
			   ,[SUBSCRIBED]
			   ,[LST_MAINT_DT]
			   ,[FILTER]
		FROM USR_C5_SUBSCRIPTION'
		EXEC (@SQL)

		DROP TABLE USR_C5_SUBSCRIPTION
		END
	ELSE
		BEGIN
		DECLARE @SQL2 VARCHAR(2000)
		SELECT @SQL2  = 'INSERT INTO [dbo].[USR_CPHIVE_SUBSCRIPTION]
			   ([SCOPE]
			   ,[SUBSCRIBED]
			   ,[LST_MAINT_DT]
			   ,[FILTER])
		SELECT	[SCOPE]
			   ,[SUBSCRIBED]
			   ,[LST_MAINT_DT]
			   ,NULL AS [FILTER]
		FROM USR_C5_SUBSCRIPTION'
		EXEC (@SQL2)

		DROP TABLE USR_C5_SUBSCRIPTION
		END
	END

IF(EXISTS(SELECT TOP 1 1 FROM Information_Schema.Tables WHERE TABLE_NAME = 'USR_C5_QUEUE')) 
	DROP TABLE USR_C5_QUEUE

